function [time,Red,Blue,Green,Activity,Battery,DaysiWatchIdHex] = importDaysiLog(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [DATE1,TIME,RED,BLUE,GREEN,ACTIVITY,BATTERY,DAYSIWATCHIDHEX] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [DATE1,TIME,RED,BLUE,GREEN,ACTIVITY,BATTERY,DAYSIWATCHIDHEX] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Date1,Time,Red,Blue,Green,Activity,Battery,DaysiWatchIdHex] =
%   importfile('DaysiLog.txt',2, 2802);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/01/22 12:59:09

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: datetimes (%{MM/dd/yyyy}D)
%	column2: datetimes (%{hh:mm:ss a}D)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{MM/dd/yy}D%{hh:mm:ss a}D%f%f%f%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Date1 = dataArray{:, 1};
Time1 = dataArray{:, 2};
Red = dataArray{:, 3};
Blue = dataArray{:, 4};
Green = dataArray{:, 5};
Activity = dataArray{:, 6};
Battery = dataArray{:, 7};
DaysiWatchIdHex = dataArray{:, 8};

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

Date1=datevec(Date1);
Time1=datevec(Time1);

time = [Date1(:,1:3), Time1(:,4:6)];


